from pydantic import BaseModel


class DepartmentCreate(BaseModel):
    #id is auto generated by database so in create we do not need id
    name: str

class DepartmentResponse(BaseModel):
    department_id: int
    name: str

    class Config:
        from_attributes = True